### ISSUE TITLE
Keeps crashing on Galaxy Note 9 (Android 9.0)

### ISSUE THREAD

**Issue by deepakkaku** [Chainfire/HideyHole#11]
Hi,

I know this app is not intended for other devices but I just love the wallpapers.
So when I tap on a wallpaper, the app immediately crashes.

there is a NullPointerException -> here is the stack trace

2019-03-19 15:52:55.160 8943-8943/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: eu.chainfire.hideyhole, PID: 8943
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List androidx.core.view.DisplayCutoutCompat.getBoundingRects()' on a null object reference
        at eu.chainfire.hideyhole.ui.CameraCutout.updateFromInsets(CameraCutout.java:156)
        at eu.chainfire.hideyhole.ui.PreviewActivity.lambda$onCreate$0(PreviewActivity.java:248)
        at eu.chainfire.hideyhole.ui.-$$Lambda$PreviewActivity$-neOAybsSZIeHCyTRbF_eGNvt5Y.onApplyWindowInsets(Unknown Source:2)
        at androidx.core.view.ViewCompat$1.onApplyWindowInsets(ViewCompat.java:2213)
        at android.view.View.dispatchApplyWindowInsets(View.java:10584)
        at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7454)
        at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7458)
        at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7458)
        at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7458)
        at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7458)
        at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7458)
        at android.view.ViewRootImpl.dispatchApplyInsets(ViewRootImpl.java:2080)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2190)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1850)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8455)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6981)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)

**Comment by deepakkaku** [comment]
Can you please make it for other devices too that don't have a cut out/notch :P please
Or just provide the wallpapers in a ZIP file
